version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dgx-ai-trainer-backend
    ports:
      - "5000:5000"
    volumes:
      - ./jobs:/app/jobs
      - ./models:/app/models
      - ./logs:/app/logs
      - ./training_scripts:/app/training_scripts
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DGX_TRAINER_BASE_DIR=/app
    # Enable GPU access with modern Compose
    gpus: all
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dgx-ai-trainer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: dgx-ai-trainer-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  jobs:
  models:
  logs:
