name: Feature Request
description: Suggest a new feature or enhancement for SparkTrainer
title: "[Feature]: "
labels: ["feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm always frustrated when...
        It would be great if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation ideas if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: |
        What other solutions or features have you considered?
        Why would your proposed solution be better?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Training Recipe
        - Data Ingestion
        - Model Evaluation
        - API Enhancement
        - UI/UX Improvement
        - Performance Optimization
        - Documentation
        - DevOps/Infrastructure
        - Security
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        What are you trying to accomplish?
        How would this feature help you?
        Who else would benefit from this?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: Provide any examples, code snippets, or mockups
      placeholder: |
        - Similar features in other tools
        - Code examples of how it might work
        - UI mockups or wireframes
        - Links to related resources

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas on how to implement this?
      placeholder: |
        If you have technical ideas on how to implement this feature,
        please share them here. This is optional but helpful!

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help document this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information about the feature request
      placeholder: Add any other context...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: This feature aligns with SparkTrainer's goals and scope
          required: true
