
seed: 1337
save_every_steps: 1000
log_every_steps: 50

train_path: data/samples.jsonl
val_path: null
max_seq_len: 8192

lr: 0.0003
weight_decay: 0.1
betas: [0.9, 0.95]
warmup_steps: 2000
total_steps: 2000

global_batch_size: 64
micro_batch_size_per_gpu: 2
grad_accum_steps: 1

out_dir: outputs/checkpoints
tensorboard_dir: outputs/tensorboard
